/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cisco.gradle;

public class App {
    public String getGreeting() {
        return "Hello world, I am your new boss Arup Sarkar.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
